[colors.bright]
black = "#505354"
blue = "#005f87"
cyan = "#008080"
green = "#5f875f"
magenta = "#9a999d"
red = "#d84949"
white = "#dadad5"
yellow = "#909495"

[colors.normal]
black = "#1b1d1e"
blue = "#005f87"
cyan = "#008080"
green = "#5f875f"
magenta = "#737271"
red = "#d84949"
white = "#c5c5be"
yellow = "#737074"

[colors.primary]
background = "#000000"
foreground = "#eeeeee"
