/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_alternativetags.h"
#include "bar_anybar.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_powerline_status.h"
#include "bar_powerline_tags.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "placemouse.h"
#include "restartsig.h"
#include "roundedcorners.h"
#include "scratchpad.h"
#include "shift.h"
#include "shiftview.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_fibonacci.h"
#include "layout_monocle.h"
#include "layout_tile.h"

