[font.normal]
#size = 13
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
decorations = "none"
opacity = 0.96

###**********catppuccin-mocha.toml**********###
[colors.primary]
background = "#111111"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"



###********** catppuccin-macchiato.toml**********###
# 
# [colors.primary]
# background = "#24273A"
# foreground = "#CAD3F5"
# dim_foreground = "#CAD3F5"
# bright_foreground = "#CAD3F5"
# 
# [colors.cursor]
# text = "#24273A"
# cursor = "#F4DBD6"
# 
# [colors.vi_mode_cursor]
# text = "#24273A"
# cursor = "#B7BDF8"
# 
# [colors.search.matches]
# foreground = "#24273A"
# background = "#A5ADCB"
# 
# [colors.search.focused_match]
# foreground = "#24273A"
# background = "#A6DA95"
# 
# [colors.footer_bar]
# foreground = "#24273A"
# background = "#A5ADCB"
# 
# [colors.hints.start]
# foreground = "#24273A"
# background = "#EED49F"
# 
# [colors.hints.end]
# foreground = "#24273A"
# background = "#A5ADCB"
# 
# [colors.selection]
# text = "#24273A"
# background = "#F4DBD6"
# 
# [colors.normal]
# black = "#494D64"
# red = "#ED8796"
# green = "#A6DA95"
# yellow = "#EED49F"
# blue = "#8AADF4"
# magenta = "#F5BDE6"
# cyan = "#8BD5CA"
# white = "#B8C0E0"
# 
# [colors.bright]
# black = "#5B6078"
# red = "#ED8796"
# green = "#A6DA95"
# yellow = "#EED49F"
# blue = "#8AADF4"
# magenta = "#F5BDE6"
# cyan = "#8BD5CA"
# white = "#A5ADCB"
# 
# [colors.dim]
# black = "#494D64"
# red = "#ED8796"
# green = "#A6DA95"
# yellow = "#EED49F"
# blue = "#8AADF4"
# magenta = "#F5BDE6"
# cyan = "#8BD5CA"
# white = "#B8C0E0"
# 
# [[colors.indexed_colors]]
# index = 16
# color = "#F5A97F"
# 
# [[colors.indexed_colors]]
# index = 17
# color = "#F4DBD6"# 