[font]
size = 11.0

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.offset]
x = 1
y = 1
